### ISSUE TITLE
Add module guard to mediator

### ISSUE THREAD

**Issue by rmeissner** [5afe/safe-protocol#5]
- [x] Allow an account to set a [guard](https://github.com/5afe/safe-protocol-specs/tree/main/components#guards-hooks)
- [x] Before and after executing a transaction via a module check the guard (if set)

**Comment by akshay-ap** [comment]
When adding a guard, should mediator check in registry if guard is listed and not flagged?

**Comment by mmv08** [comment]
> When adding a guard, should mediator check in registry if guard is listed and not flagged?

Makes sense to me. But this should be clarified in the specs
